In [123]:
parseInt(x) = parse(Int, x)

parseInt (generic function with 1 method)

In [124]:
raw_lines = readlines("input.txt")

601-element Vector{String}:
 "79,9,13,43,53,51,40,47,56,27,0," ⋯ 228 bytes ⋯ ",3,46,67,90,62,20,5,52,99,81,4"
 ""
 " 7 42 22 92 60"
 " 8 88 99 13 12"
 "16 62 86 24 77"
 "20 57 19 67 46"
 "36 83 54 63 82"
 ""
 " 7 86 50 78 16"
 "83 45 67 94 58"
 "21 98 99 85 43"
 "71 19 31 22  4"
 "70 51 34 11 61"
 ⋮
 ""
 " 0 69 51 12 82"
 " 4 81 62  2 49"
 "27 66 95 83 70"
 "94 97 99 63 19"
 "87 75 77 73 44"
 ""
 "82 83 75 95 53"
 "46 47 31 14 64"
 "71 70 11 51 87"
 " 7 16 63 38 29"
 "89 13 33 41  0"

In [125]:
function split_lines(lines)
    result = Vector{String}[]
    current = String[]
    for l in lines
        if isempty(l)
            push!(result, current)
            current = String[]
        else
            push!(current, l)
        end
    end
    if !isempty(current)
        push!(result, current)
    end
    return result
end

split_lines (generic function with 1 method)

In [126]:
groups = split_lines(raw_lines)

101-element Vector{Vector{String}}:
 ["79,9,13,43,53,51,40,47,56,27,0,14,33,60,61,36,72,48,83,42,10,86,41,75,16,80,15,93,95,45,68,96,84,11,85,63,18,31,35,74,71,91,39,88,55,6,21,12,58,29,69,37,44,98,89,78,17,64,59,76,54,30,65,82,28,50,32,77,66,24,1,70,92,23,8,49,38,73,94,26,22,34,97,25,87,19,57,7,2,3,46,67,90,62,20,5,52,99,81,4"]
 [" 7 42 22 92 60", " 8 88 99 13 12", "16 62 86 24 77", "20 57 19 67 46", "36 83 54 63 82"]
 [" 7 86 50 78 16", "83 45 67 94 58", "21 98 99 85 43", "71 19 31 22  4", "70 51 34 11 61"]
 [" 4 95 84 51 36", "43 40 37 23 85", "14 90  8 59 99", " 0 88 68 93 81", "25  6 55 19 48"]
 ["15 39 78  6 13", "71  3 81 95 62", "22 46 67 72 40", "89 69  0 37 41", "68 79 58 16 42"]
 ["63 50 77 34 12", "29 42 20 17 47", "80 10 30 72 66", " 5 89 64 25 21", "91 88 45 44 37"]
 ["78 89 32 26 56", " 8 40 54 25 49", "36 30 21 23  3", "12 58  2 29  7", "33 99 15 84 44"]
 ["96 68 56 49 43", "55 22 16 91 32", " 2 17 61 12 37", "25 72  1 31 88", "57 34 42  8 71"]
 ["18 39 86 94 60", "96 8

In [127]:
function matrixize(lines)
    get_row(line) = split(line) .|> parseInt
    rows = get_row.(lines)
    return hcat(rows...)'
end

matrixize (generic function with 1 method)

In [128]:
chosen_numbers = split(groups[1][1], ",") .|> parseInt

100-element Vector{Int64}:
 79
  9
 13
 43
 53
 51
 40
 47
 56
 27
  0
 14
 33
  ⋮
  2
  3
 46
 67
 90
 62
 20
  5
 52
 99
 81
  4

In [129]:
matrixs = matrixize.(groups[2:end])

100-element Vector{LinearAlgebra.Adjoint{Int64, Matrix{Int64}}}:
 [7 42 … 92 60; 8 88 … 13 12; … ; 20 57 … 67 46; 36 83 … 63 82]
 [7 86 … 78 16; 83 45 … 94 58; … ; 71 19 … 22 4; 70 51 … 11 61]
 [4 95 … 51 36; 43 40 … 23 85; … ; 0 88 … 93 81; 25 6 … 19 48]
 [15 39 … 6 13; 71 3 … 95 62; … ; 89 69 … 37 41; 68 79 … 16 42]
 [63 50 … 34 12; 29 42 … 17 47; … ; 5 89 … 25 21; 91 88 … 44 37]
 [78 89 … 26 56; 8 40 … 25 49; … ; 12 58 … 29 7; 33 99 … 84 44]
 [96 68 … 49 43; 55 22 … 91 32; … ; 25 72 … 31 88; 57 34 … 8 71]
 [18 39 … 94 60; 96 85 … 51 28; … ; 6 84 … 90 81; 43 41 … 68 32]
 [9 58 … 7 61; 96 33 … 0 19; … ; 13 36 … 95 29; 86 91 … 72 20]
 [3 79 … 37 97; 86 10 … 31 32; … ; 65 21 … 82 36; 26 51 … 12 99]
 [66 28 … 6 32; 11 30 … 42 76; … ; 46 88 … 50 64; 86 71 … 36 80]
 [36 34 … 68 49; 61 3 … 84 71; … ; 25 51 … 59 62; 90 21 … 52 8]
 [19 93 … 40 55; 41 11 … 9 70; … ; 12 4 … 60 0; 36 77 … 33 83]
 ⋮
 [10 85 … 38 22; 46 35 … 12 27; … ; 55 57 … 9 49; 79 73 … 1 21]
 [52 36 … 82 91; 22 7 … 21 12; … ;

In [130]:
winner_mask(number, matrix) = matrix .== number

zerosInt(size) = zeros(Int, size)

function is_winner(grid)
    return (maximum(sum(grid, dims = 1)) == 5) || (maximum(sum(grid, dims = 2)) == 5)
end

function get_winner(numbers, matrixs)
    grids = map(zerosInt ∘ size, matrixs)
    for number in numbers
        for i in 1:length(matrixs)
            grids[i] = grids[i] .| winner_mask(number, matrixs[i])
            if is_winner(grids[i])
                return matrixs[i], grids[i], number
            end
        end
    end
end

function part1(numbers, matrixs)
    matrix, grid, number = get_winner(numbers, matrixs)
    unmarked_numbers = iszero.(grid) .* matrix
    return sum(unmarked_numbers) * number
end

part1 (generic function with 1 method)

In [131]:
part1(chosen_numbers, matrixs)

44736

In [132]:
function get_loser(numbers, matrixs)
    grids = map(zerosInt ∘ size, matrixs)
    for number in numbers
        for i in 1:length(matrixs)
            grids[i] = grids[i] .| winner_mask(number, matrixs[i])
            not_winners = filter(!is_winner, grids)
            if length(not_winners) == 0
                return matrixs[i], grids[i], number
            end
        end
    end
end

function part2(numbers, matrixs)
    matrix, grid, number = get_loser(numbers, matrixs)
    unmarked_numbers = iszero.(grid) .* matrix
    return sum(unmarked_numbers) * number
end

part2 (generic function with 1 method)

In [133]:
part2(chosen_numbers, matrixs)

1827